SELECT tablespace_name from dba_tablespaces;
CREATE TABLESPACE tbs1 DATAFILE 'C:\app\Shubham\product\21c\tbs1.dbf' SIZE 50M;
SHOW CON_NAME;
SELECT NAME FROM V$PDBS;

ALTER SESSION SET CONTAINER = CDB$ROOT;


SELECT NAME, OPEN_MODE FROM V$PDBS;
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER shubham  IDENTIFIED BY shubham DEFAULT TABLESPACE TBS01 QUOTA 5M ON TBS01;
GRANT CONNECT, RESOURCE TO ellison;



DROP TABLESPACE TBS01;